=== api-evangelist/amazon-ecs/json-schema/amazon-ecs-container-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Container",
  "type": "object",
  "description": "A container that is part of a task.",
  "properties": {
    "containerArn": {
      "type": "string"
    },
    "taskArn": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "imageDigest": {
      "type": "string"
    },
    "runtimeId": {
      "type": "string"
    },
    "lastStatus": {
      "type": "string"
    },
    "exitCode": {
      "type": "integer"
    },
    "reason": {
      "type": "string"
    },
    "healthStatus": {
      "type": "string"
    },
    "cpu": {
      "type": "string"
    },
    "memory": {
      "type": "string"
    },
    "memoryReservation": {
      "type": "string"
    },
    "gpuIds": {
      "type": "array"
    },
    "networkBindings": {
      "type": "array"
    },
    "networkInterfaces": {
      "type": "array"
    },
    "managedAgents": {
      "type": "array"
    }
  }
}

=== api-evangelist/amazon-ecs/examples/amazon-ecs-container-example.json
{
  "containerArn": "example_value",
  "taskArn": "example_value",
  "name": "Example Title",
  "image": "example_value",
  "imageDigest": "example_value",
  "runtimeId": "500123",
  "lastStatus": "example_value",
  "exitCode": 10,
  "reason": "example_value",
  "healthStatus": "example_value",
  "cpu": "example_value",
  "memory": "example_value",
  "memoryReservation": "example_value",
  "gpuIds": [],
  "networkBindings": [],
  "networkInterfaces": [],
  "managedAgents": []
}
