=== api-evangelist/amazon-ecs/json-schema/amazon-ecs-deployment-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Deployment",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "taskDefinition": {
      "type": "string"
    },
    "desiredCount": {
      "type": "integer"
    },
    "pendingCount": {
      "type": "integer"
    },
    "runningCount": {
      "type": "integer"
    },
    "failedTasks": {
      "type": "integer"
    },
    "createdAt": {
      "type": "number"
    },
    "updatedAt": {
      "type": "number"
    },
    "launchType": {
      "type": "string"
    },
    "platformVersion": {
      "type": "string"
    },
    "platformFamily": {
      "type": "string"
    },
    "rolloutState": {
      "type": "string"
    },
    "rolloutStateReason": {
      "type": "string"
    },
    "capacityProviderStrategy": {
      "type": "array"
    }
  }
}

=== api-evangelist/amazon-ecs/examples/amazon-ecs-deployment-example.json
{
  "id": "abc123",
  "status": "example_value",
  "taskDefinition": "example_value",
  "desiredCount": 10,
  "pendingCount": 10,
  "runningCount": 10,
  "failedTasks": 10,
  "createdAt": 42.5,
  "updatedAt": 42.5,
  "launchType": "example_value",
  "platformVersion": "example_value",
  "platformFamily": "example_value",
  "rolloutState": "example_value",
  "rolloutStateReason": "example_value",
  "capacityProviderStrategy": []
}
