=== api-evangelist/amazon-ecs/json-schema/amazon-ecs-create-service-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "CreateServiceRequest",
  "type": "object",
  "properties": {
    "serviceName": {
      "type": "string",
      "description": "The name of your service (up to 255 characters)."
    },
    "cluster": {
      "type": "string",
      "description": "The short name or full ARN of the cluster to run the service on."
    },
    "taskDefinition": {
      "type": "string",
      "description": "The family and revision or full ARN of the task definition."
    },
    "desiredCount": {
      "type": "integer",
      "description": "The number of instantiations of the specified task definition to place and keep running."
    },
    "launchType": {
      "type": "string",
      "description": "The launch type on which to run your service."
    },
    "capacityProviderStrategy": {
      "type": "array"
    },
    "platformVersion": {
      "type": "string",
      "description": "The platform version that your tasks in the service are running on (Fargate only)."
    },
    "loadBalancers": {
      "type": "array",
      "description": "A load balancer object representing the load balancers to use with your service."
    },
    "schedulingStrategy": {
      "type": "string",
      "description": "The scheduling strategy to use for the service."
    },
    "placementConstraints": {
      "type": "array"
    },
    "placementStrategy": {
      "type": "array"
    },
    "healthCheckGracePeriodSeconds": {
      "type": "integer",
      "description": "The period of time, in seconds, that the ECS service scheduler ignores unhealthy Elastic Load Balancing target health checks after a task has first started."
    },
    "enableECSManagedTags": {
      "type": "boolean"
    },
    "enableExecuteCommand": {
      "type": "boolean",
      "description": "Whether to enable Amazon ECS Exec for the tasks within the service."
    },
    "propagateTags": {
      "type": "string"
    },
    "role": {
      "type": "string",
      "description": "The IAM role that allows Amazon ECS to make calls to your load balancer."
    },
    "serviceRegistries": {
      "type": "array"
    },
    "tags": {
      "type": "array"
    },
    "clientToken": {
      "type": "string",
      "description": "An identifier you provide to ensure the idempotency of the request."
    }
  }
}

=== api-evangelist/amazon-ecs/examples/amazon-ecs-create-service-request-example.json
{
  "serviceName": "example_value",
  "cluster": "example_value",
  "taskDefinition": "example_value",
  "desiredCount": 10,
  "launchType": "example_value",
  "capacityProviderStrategy": [],
  "platformVersion": "example_value",
  "loadBalancers": [],
  "schedulingStrategy": "example_value",
  "placementConstraints": [],
  "placementStrategy": [],
  "healthCheckGracePeriodSeconds": 10,
  "enableECSManagedTags": true,
  "enableExecuteCommand": true,
  "propagateTags": "example_value",
  "role": "example_value",
  "serviceRegistries": [],
  "tags": [],
  "clientToken": "example_value"
}
