=== api-evangelist/amazon-ecs/json-schema/amazon-ecs-run-task-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "RunTaskRequest",
  "type": "object",
  "properties": {
    "taskDefinition": {
      "type": "string",
      "description": "The family and revision or full ARN of the task definition to run."
    },
    "cluster": {
      "type": "string",
      "description": "The short name or full ARN of the cluster to run the task on."
    },
    "count": {
      "type": "integer",
      "description": "The number of instantiations of the specified task to place on your cluster (1-10)."
    },
    "launchType": {
      "type": "string",
      "description": "The launch type on which to run your task."
    },
    "capacityProviderStrategy": {
      "type": "array"
    },
    "platformVersion": {
      "type": "string",
      "description": "The platform version the task uses (Fargate launch type only)."
    },
    "placementConstraints": {
      "type": "array"
    },
    "placementStrategy": {
      "type": "array"
    },
    "group": {
      "type": "string",
      "description": "The name of the task group to associate with the task."
    },
    "startedBy": {
      "type": "string",
      "description": "An optional tag specified when a task is started."
    },
    "tags": {
      "type": "array"
    },
    "enableECSManagedTags": {
      "type": "boolean"
    },
    "enableExecuteCommand": {
      "type": "boolean",
      "description": "Whether to enable Amazon ECS Exec for the task."
    },
    "propagateTags": {
      "type": "string"
    },
    "clientToken": {
      "type": "string",
      "description": "An identifier you provide to ensure the idempotency of the request."
    }
  }
}

=== api-evangelist/amazon-ecs/examples/amazon-ecs-run-task-request-example.json
{
  "taskDefinition": "example_value",
  "cluster": "example_value",
  "count": 10,
  "launchType": "example_value",
  "capacityProviderStrategy": [],
  "platformVersion": "example_value",
  "placementConstraints": [],
  "placementStrategy": [],
  "group": "example_value",
  "startedBy": "example_value",
  "tags": [],
  "enableECSManagedTags": true,
  "enableExecuteCommand": true,
  "propagateTags": "example_value",
  "clientToken": "example_value"
}
