=== api-evangelist/amazon-ecs/json-schema/amazon-ecs-task-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Task",
  "type": "object",
  "description": "Details on a task in a cluster.",
  "properties": {
    "taskArn": {
      "type": "string",
      "description": "The ARN of the task."
    },
    "clusterArn": {
      "type": "string",
      "description": "The ARN of the cluster that hosts the task."
    },
    "taskDefinitionArn": {
      "type": "string",
      "description": "The ARN of the task definition that creates the task."
    },
    "containerInstanceArn": {
      "type": "string",
      "description": "The ARN of the container instances that host the task."
    },
    "lastStatus": {
      "type": "string",
      "description": "The last known status for the task."
    },
    "desiredStatus": {
      "type": "string",
      "description": "The desired status of the task."
    },
    "cpu": {
      "type": "string"
    },
    "memory": {
      "type": "string"
    },
    "containers": {
      "type": "array"
    },
    "startedBy": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "stoppedReason": {
      "type": "string"
    },
    "stopCode": {
      "type": "string"
    },
    "connectivity": {
      "type": "string"
    },
    "connectivityAt": {
      "type": "number"
    },
    "pullStartedAt": {
      "type": "number"
    },
    "pullStoppedAt": {
      "type": "number"
    },
    "executionStoppedAt": {
      "type": "number"
    },
    "createdAt": {
      "type": "number"
    },
    "startedAt": {
      "type": "number"
    },
    "stoppingAt": {
      "type": "number"
    },
    "stoppedAt": {
      "type": "number"
    },
    "group": {
      "type": "string"
    },
    "launchType": {
      "type": "string"
    },
    "platformVersion": {
      "type": "string"
    },
    "platformFamily": {
      "type": "string"
    },
    "capacityProviderName": {
      "type": "string"
    },
    "availabilityZone": {
      "type": "string"
    },
    "attachments": {
      "type": "array"
    },
    "healthStatus": {
      "type": "string"
    },
    "enableExecuteCommand": {
      "type": "boolean"
    },
    "tags": {
      "type": "array"
    },
    "inferenceAccelerators": {
      "type": "array"
    },
    "attributes": {
      "type": "array"
    }
  }
}

=== api-evangelist/amazon-ecs/examples/amazon-ecs-task-example.json
{
  "taskArn": "example_value",
  "clusterArn": "example_value",
  "taskDefinitionArn": "example_value",
  "containerInstanceArn": "example_value",
  "lastStatus": "example_value",
  "desiredStatus": "example_value",
  "cpu": "example_value",
  "memory": "example_value",
  "containers": [],
  "startedBy": "example_value",
  "version": 10,
  "stoppedReason": "example_value",
  "stopCode": "example_value",
  "connectivity": "example_value",
  "connectivityAt": 42.5,
  "pullStartedAt": 42.5,
  "pullStoppedAt": 42.5,
  "executionStoppedAt": 42.5,
  "createdAt": 42.5,
  "startedAt": 42.5,
  "stoppingAt": 42.5,
  "stoppedAt": 42.5,
  "group": "example_value",
  "launchType": "example_value",
  "platformVersion": "example_value",
  "platformFamily": "example_value",
  "capacityProviderName": "example_value",
  "availabilityZone": "example_value",
  "attachments": [],
  "healthStatus": "example_value",
  "enableExecuteCommand": true,
  "tags": [],
  "inferenceAccelerators": [],
  "attributes": []
}
